sudo: required

language: php

git:
  submodules: false

services:
  - docker

before_install:
  - sed -i 's/LaraDock\/laradock:/LaraDock\/laradock//' .gitmodules
  - git submodule update --init --recursive
  - cd laradock
  - docker-compose up -d caddy postgres php-fpm redis beanstalkd elasticsearch
  - docker ps -a
  - docker-compose exec workspace bash -c "/var/www/vendor/bin/phpunit"
