language: php
php:
  - '7.0'
sudo: false
services:
  - elasticsearch
  - postgres
install:
  - export PATH=$PATH:$PWD/vendor/bin/
  - mkdir -p build/logs
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone https://github.com/nikic/php-ast.git
  - cd php-ast
  - phpize
  - ./configure
  - make install
  - composer install --no-interaction --no-scripts
  - composer require satooshi/php-coveralls:dev-master
  - cp -n .env.travis .env
  - nvm install 6 && nvm use 6
  - rm -rf node_modules
  - npm install -g npm
  - npm cache verify
  - npm install --no-progress
  - npm install --no-progress -g gulp
  - npm rebuild node-sass
  - bundler install
  - gulp
  - php artisan key:generate
  - php artisan storage:link
  - php artisan route:cache; php artisan config:cache; php artisan optimize
script:
  - make test
after_success:
  - travis_retry php vendor/bin/coveralls -v
