language: php
php:
  - '7.1'
sudo: false
services:
  - elasticsearch
  - postgres
install:
  - export PATH=$PATH:$PWD/vendor/bin/
  - mkdir -p build/logs
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - (./infrastructure/install/install-php-ast.sh)
  - composer install --no-interaction --no-scripts
  - composer require satooshi/php-coveralls:dev-master
  - cp -n .env.travis .env
  - nvm install 6 && nvm use 6
  - npm install -g npm
  - make install
  - gulp
  - php artisan key:generate
  - php artisan storage:link
  - php artisan route:cache; php artisan config:cache; php artisan optimize
script:
  - make test
after_success:
  - travis_retry php vendor/bin/coveralls -v
